### ISSUE TITLE
Can't Install Gem

### ISSUE THREAD

**Issue by paulsuk** [red-data-tools/extpp#2]
Hi, I am unable to install this Gem, I am currently running Ruby v2.3.0p0, (need to use this version), on an OSX system.

When I run: ` $ gem install extpp `

I get this error: 

```
Building native extensions.  This could take a while...
ERROR:  Error installing extpp:
	ERROR: Failed to build gem native extension.

    current directory: /Users/evichat2/.rvm/gems/ruby-2.3.0/gems/extpp-0.0.2/ext/extpp
/Users/evichat2/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20180216-1258-1uglb1i.rb extconf.rb
checking --enable-debug-build option... no
checking g++ version... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/evichat2/.rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
	--enable-debug-build
	--disable-debug-build
/Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:943:in `%': can't convert nil into Float (TypeError)
	from /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:943:in `block in checking_for'
	from /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /Users/evichat2/.rvm/gems/ruby-2.3.0/gems/extpp-0.0.2/lib/extpp/compiler.rb:33:in `check_version'
	from /Users/evichat2/.rvm/gems/ruby-2.3.0/gems/extpp-0.0.2/lib/extpp/compiler.rb:16:in `check'
	from extconf.rb:5:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/evichat2/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-17/2.3.0/extpp-0.0.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/evichat2/.rvm/gems/ruby-2.3.0/gems/extpp-0.0.2 for inspection.
Results logged to /Users/evichat2/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-17/2.3.0/extpp-0.0.2/gem_make.out
```

As well, when checking the mkmf.log file, this is it:
```
Provided configuration options:
check_debug_build: checking --enable-debug-build option... -------------------- no

--------------------

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
```

Thanks in advance for your work!

**Comment by kou** [comment]
Can you try 0.0.3?

**Comment by paulsuk** [comment]
Works now, thank you!

**Comment by paulsuk** [comment]
Hi, I'm having two separate additional issues:

1) when using your provided 'hello' example:
```
$ ruby extconf.rb;make;ruby -r ./hello -e 'p Hello.new("me").greet'
checking --enable-debug-build option... no
checking g++ version... 9 (gnu++14)
creating Makefile
linking shared-object hello.bundle
/Users/evichat2/Documents/Workspace/extpp_test/hello.bundle: [BUG] Segmentation fault at 0x00000000000438
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin17]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0004 p:-17589875659002 s:0019 e:000018 TOP    [FINISH]
c:0003 p:---- s:0017 e:000016 CFUNC  :require
c:0002 p:0132 s:0013 e:000012 METHOD /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59 [FINISH]
c:0001 p:0000 s:0002 E:001430 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'

-- Machine register context ------------------------------------------------
 rax: 0x0000000000000030 rbx: 0x0000000105f33ed0 rcx: 0x0000000000000000
 rdx: 0xfffffffffffffff0 rdi: 0x0000000000000030 rsi: 0x0000000000000000
 rbp: 0x00007ffeea1376a0 rsp: 0x00007ffeea1376a0  r8: 0x00000000bb40213f
  r9: 0x0000000000000017 r10: 0x0000000080000000 r11: 0x00007ffbb4000000
 r12: 0x00007ffbb28da620 r13: 0x00007ffbb2904790 r14: 0x0000000000000005
 r15: 0x00007ffbb28e1998 rip: 0x00007fff3422384b rfl: 0x0000000000010246

-- C level backtrace information -------------------------------------------
0   libruby.2.3.0.dylib                 0x0000000105c72909 rb_vm_bugreport + 377
1   libruby.2.3.0.dylib                 0x0000000105b14d54 rb_bug_context + 452
2   libruby.2.3.0.dylib                 0x0000000105be7064 sigsegv + 68
3   libsystem_platform.dylib            0x00007fff509b2f5a _sigtramp + 26
4   Ruby                                0x00007fff3422384b ruby_xmalloc + 17
5   ???                                 0x00007ffeea1376c0 0x0 + 140732825564864

-- Other runtime information -----------------------------------------------

* Loaded script: -e

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin17/enc/encdb.bundle
    5 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin17/enc/trans/transdb.bundle
    6 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/unicode_normalize.rb
    7 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin17/rbconfig.rb
    8 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/compatibility.rb
    9 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/defaults.rb
   10 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/deprecate.rb
   11 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/errors.rb
   12 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/version.rb
   13 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb
   14 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/platform.rb
   15 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb
   16 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb
   17 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/util/list.rb
   18 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin17/stringio.bundle
   19 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/rfc2396_parser.rb
   20 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/rfc3986_parser.rb
   21 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/common.rb
   22 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/generic.rb
   23 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/ftp.rb
   24 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/http.rb
   25 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/https.rb
   26 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/ldap.rb
   27 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/ldaps.rb
   28 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/mailto.rb
   29 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri.rb
   30 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb
   31 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/exceptions.rb
   32 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb
   33 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_gem.rb
   34 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb
   35 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb
   36 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems.rb
   37 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/path_support.rb
   38 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/bundler_version_finder.rb
   39 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/util.rb
   40 /Users/evichat2/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean/version.rb
   41 /Users/evichat2/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb
   42 /Users/evichat2/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean/levenshtein.rb
   43 /Users/evichat2/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean/jaro_winkler.rb
   44 /Users/evichat2/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkable.rb
   45 /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/delegate.rb
   46 /Users/evichat2/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   47 /Users/evichat2/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   48 /Users/evichat2/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   49 /Users/evichat2/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   50 /Users/evichat2/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/null_checker.rb
   51 /Users/evichat2/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean/formatter.rb
   52 /Users/evichat2/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
```

I get this segmentation fault

2) When I try my own example, in my own project directory, I get this issue:

```
ruby extconf.rb;make;irb
checking --enable-debug-build option... no
checking g++ version... 9 (gnu++14)
creating Makefile
compiling hello.cpp
compiling ruby_fasttext.cpp
linking shared-object hello.bundle
2.3.0 :001 > require './hello'
LoadError: dlopen(/Users/evichat2/Documents/Workspace/ruby_fasttext/hello.bundle, 9): Symbol not found: __ZN8fasttext10Dictionary3EOSE
  Referenced from: /Users/evichat2/Documents/Workspace/ruby_fasttext/hello.bundle
  Expected in: flat namespace
 in /Users/evichat2/Documents/Workspace/ruby_fasttext/hello.bundle - /Users/evichat2/Documents/Workspace/ruby_fasttext/hello.bundle
	from /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/evichat2/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from (irb):1
	from /Users/evichat2/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

**Comment by paulsuk** [comment]
To be clear, the installation of the Gem worked

**Comment by kou** [comment]
Can you use one issue for one problem instead of reusing existing issue?
